### ISSUE TITLE
Not IE compatible

### ISSUE THREAD

**Issue by Bastien7** [fapfapjs/fapfapjs#1]
Hello,

Thanks to contribute to create a better world for developers. Your project is certainly the best revelation of the year and a big source of inspiration for every front-end developers. I have put it in production in my company, it works great and customers gave us really good feedback.
But I have a problem, it seems to not be compatible for IE6, did you plan to fix this problem ?

**Comment by ClementGautier** [comment]
We have our hands on it actually but it takes time to fix it ;)

**Comment by juliensnz** [comment]
Yeah, supporting IE6 is essential. As FapFap is universal and for everyone we should fix this issue as soon as possible.
